#define LWIP_PREFIX_BYTEORDER_FUNCS
#define LWIP_PROVIDE_ERRNO
#define LWIP_ARP 1
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define MEM_USE_POOLS 0
#define LWIP_CHECKSUM_CTRL_PER_NETIF 1
#define LWIP_RAW 1
#define LWIP_NETIF_API 1
