obj-y := def.o dns.o inet_chksum.o init.o ip.o mem.o memp.o netif.o pbuf.o raw.o stats.o sys.o tcp_in.o tcp_out.o tcp.o timers.o udp.o sys_arch.o
dirs-y := ipv4 ipv6
TARGET_CFLAGS += -iquote../include
